

MACRO(INSTALL_HEADER   LIB_NAME   LIB_H_FILES)
    INSTALL( FILES      ${${LIB_H_FILES}}
        DESTINATION     include/${LIB_NAME}
        COMPONENT       headers
    )
ENDMACRO()



MACRO(INSTALL_LIBRARY   LIB_NAME   LIB_H_FILES)
    INSTALL(TARGETS   ${LIB_NAME}
        RUNTIME   DESTINATION bin    COMPONENT binaries
        LIBRARY   DESTINATION lib    COMPONENT libraries
        ARCHIVE   DESTINATION lib    COMPONENT libraries
    )

    INSTALL_HEADER(${LIB_NAME}   ${LIB_H_FILES})
ENDMACRO()



MACRO(INSTALL_HEADER_WITH_PREFIX   LIB_NAME   PREFIX_NAME   LIB_H_FILES)
    INSTALL( FILES      ${${LIB_H_FILES}}
        DESTINATION     ${PREFIX_NAME}/include/${LIB_NAME}
        COMPONENT       headers
    )
ENDMACRO()



MACRO(INSTALL_LIBRARY_WITH_PREFIX   LIB_NAME   PREFIX_NAME   LIB_H_FILES)
    INSTALL(TARGETS   ${LIB_NAME}
        RUNTIME   DESTINATION ${PREFIX_NAME}/bin    COMPONENT binaries
        LIBRARY   DESTINATION ${PREFIX_NAME}/lib    COMPONENT libraries
        ARCHIVE   DESTINATION ${PREFIX_NAME}/lib    COMPONENT libraries
    )

    INSTALL_HEADER_WITH_PREFIX(${LIB_NAME}   ${PREFIX_NAME}   ${LIB_H_FILES})
ENDMACRO()