
MACRO(SETUP_QT_LIBRARY   LIB_NAME   LIB_H_FILES   LIB_CPP_FILES   LIB_UI_FILES)
    INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})
    
    CONFIGURE_LIBRARY_GENERAL_HEADER(${LIB_NAME}   ${LIB_H_FILES})
    
    ADD_LIBRARY( ${LIB_NAME}
         ${${LIB_H_FILES}}
         ${${LIB_CPP_FILES}}
         ${${LIB_UI_FILES}}
    )
    
    ADD_STATIC_POSTFIX_IF_NEEDED(${LIB_NAME})
    
    INSTALL_LIBRARY(${LIB_NAME}   ${LIB_H_FILES})
ENDMACRO()

