

MACRO(CONFIGURE_CPACK_APPLICATION_VERSION   VER_MAJOR   VER_MINOR   VER_PATCH)
    set(CPACK_PACKAGE_VERSION_MAJOR ${VER_MAJOR})
    set(CPACK_PACKAGE_VERSION_MINOR ${VER_MINOR})
    set(CPACK_PACKAGE_VERSION_PATCH ${VER_PATCH})
    set(CPACK_PACKAGE_VERSION       "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
ENDMACRO()



MACRO(INITIALIZE_CPACK_NSIS_PROPERTY_FILE)
    if(EXISTS    "${CMAKE_BINARY_DIR}/CPackOptions.cmake")
        FILE(REMOVE   "${CMAKE_BINARY_DIR}/CPackOptions.cmake")
    endif()
    FILE(WRITE   "${CMAKE_BINARY_DIR}/CPackOptions.cmake")
ENDMACRO()



MACRO(APPEND_CPACK_NSIS_PROPERTY   VAR_NAME   VAR_DATA)
    if(NOT DEFINED  CPACK_PROPERTIES_FILE)
        set(CPACK_PROPERTIES_FILE   "${CMAKE_BINARY_DIR}/CPackOptions.cmake")
    endif()
    set(PROPERTY_TEXT)
    if(EXISTS    "${CMAKE_BINARY_DIR}/CPackOptions.cmake")
        FILE(READ   "${CMAKE_BINARY_DIR}/CPackOptions.cmake"   PROPERTY_TEXT)
    endif()
    set(PROPERTY_TEXT "${PROPERTY_TEXT}SET(${VAR_NAME}  \"${VAR_DATA}\")\n")
    FILE(WRITE   "${CMAKE_BINARY_DIR}/CPackOptions.cmake"   ${PROPERTY_TEXT})
ENDMACRO()



MACRO(INCLUDE_ENVVARUPDATE_FILE_IN_NSIS_TEMPLATE)
    find_path(CMAKE_DIR_WITH_CPACK_FILES   cpack/EnvVarUpdate.nsh
        PATHS ${CMAKE_MODULE_PATH}
        NO_DEFAULT_PATH
    )
    set(CMAKE_ENVVARUPDATE_NSH ${CMAKE_DIR_WITH_CPACK_FILES}/cpack/EnvVarUpdate.nsh)
    string(REPLACE "/" "\\\\\\\\" CMAKE_ENVVARUPDATE_NSH ${CMAKE_ENVVARUPDATE_NSH})
    APPEND_CPACK_NSIS_PROPERTY(INCLUDE_ENVVARUPDATE_NSH   "  !include \\\\\\\"${CMAKE_ENVVARUPDATE_NSH}\\\\\\\"")
ENDMACRO()



MACRO(CONFIGURE_CPACK_GENERATION   PACK_NAME   INSTALL_NAME   README_PATH   LICENCE_PATH   ICON_PNG   ICON_ICO)

    set(CPACK_PACKAGE_NAME                  "${PACK_NAME}")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY   "Project: ${PACK_NAME}")
    set(CPACK_PACKAGE_VENDOR                "Joseph Salini")
    set(CPACK_PACKAGE_DESCRIPTION_FILE      "${README_PATH}")
    set(CPACK_RESOURCE_FILE_LICENSE         "${LICENCE_PATH}")
    set(CPACK_PACKAGE_INSTALL_DIRECTORY     "${INSTALL_NAME}")
    set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY  "${PACK_NAME}")
    set(CPACK_PACKAGE_ICON                  "${ICON_PNG}")

    if (WIN32)
        INITIALIZE_CPACK_NSIS_PROPERTY_FILE()
        
        set(CPACK_GENERATOR NSIS)
        set(CPACK_NSIS_DISPLAY_NAME     "${PACK_NAME}")
        set(CPACK_NSIS_PACKAGE_NAME     "${PACK_NAME}")
        set(CPACK_NSIS_CONTACT          "josephsalini@gmail.com")
        set(CPACK_NSIS_MUI_ICON         "${ICON_ICO}")
        set(CPACK_NSIS_MUI_UNIICON      "${ICON_ICO}")
        
        INCLUDE_ENVVARUPDATE_FILE_IN_NSIS_TEMPLATE()
    endif()

ENDMACRO()